apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/resources/
bases:
  - git@github.com:moredhel/remote-kustomize.git?ref=v0.0.1
  - git@github.com:renovatebot/renovate.git/tools?ref=23.47.0
  - github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6
  - somedir/

resources:
  - git@github.com:kubernetes/kubernetes.git?ref=v1.18.0
  - https://gitlab.com/gitlab-org/gitlab-foss.git?ref=v13.4.2
  - https://gitlab.com/gnachman/iterm2.git/somedir?ref=v3.3.8

